from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    return LaunchDescription(
        [
            DeclareLaunchArgument("image_topic", default_value=""),
            DeclareLaunchArgument("compressed_image_topic", default_value=""),
            DeclareLaunchArgument("odom_topic", default_value="/chassis/odom"),
            DeclareLaunchArgument("require_fresh_image", default_value="false"),
            DeclareLaunchArgument("nav_timeout_sec", default_value="240.0"),
            DeclareLaunchArgument("nav_feedback_log_interval_sec", default_value="5.0"),
            DeclareLaunchArgument("inference_mode", default_value="server"),
            DeclareLaunchArgument("allow_inference_fallback", default_value="false"),
            DeclareLaunchArgument("force_cpu", default_value="false"),
            DeclareLaunchArgument("gpu_device", default_value="0"),
            DeclareLaunchArgument("model_startup_timeout_sec", default_value="300.0"),
            DeclareLaunchArgument("inference_request_timeout_sec", default_value="180.0"),
            DeclareLaunchArgument(
                "model_python_executable",
                default_value="/home/bluepoisons/miniconda3/envs/isaaclab/bin/python",
            ),
            DeclareLaunchArgument(
                "live_image_snapshot_dir",
                default_value="/home/bluepoisons/Desktop/FURP/VLN/ZhiruiSHEN-VLN/data/runtime/trial_images",
            ),
            DeclareLaunchArgument("visual_scan_enabled", default_value="true"),
            DeclareLaunchArgument("visual_scan_steps", default_value="8"),
            DeclareLaunchArgument("visual_scan_step_rad", default_value="0.7853981633974483"),
            DeclareLaunchArgument("visual_scan_settle_sec", default_value="1.0"),
            DeclareLaunchArgument("visual_scan_min_confidence", default_value="0.6"),
            DeclareLaunchArgument("visual_scan_spin_time_allowance_sec", default_value="15.0"),
            DeclareLaunchArgument("visual_scan_spin_mode", default_value="cmd_vel"),
            DeclareLaunchArgument("visual_scan_angular_speed_rad_s", default_value="0.35"),
            DeclareLaunchArgument("cmd_vel_topic", default_value="/cmd_vel"),
            DeclareLaunchArgument("semantic_exploration_enabled", default_value="true"),
            DeclareLaunchArgument("clear_costmaps_before_nav", default_value="true"),
            DeclareLaunchArgument("nav_retry_on_stuck", default_value="true"),
            DeclareLaunchArgument("nav_max_retries", default_value="1"),
            DeclareLaunchArgument("nav_accept_distance_m", default_value="0.30"),
            DeclareLaunchArgument("nav_accept_distance_hold_sec", default_value="2.0"),
            DeclareLaunchArgument("nav_stuck_timeout_sec", default_value="45.0"),
            DeclareLaunchArgument("nav_stuck_min_progress_m", default_value="0.15"),
            DeclareLaunchArgument("nav_stuck_recovery_backup_speed_m_s", default_value="-0.10"),
            DeclareLaunchArgument("nav_stuck_recovery_backup_duration_sec", default_value="1.0"),
            DeclareLaunchArgument("nav_stuck_recovery_turn_speed_rad_s", default_value="0.35"),
            DeclareLaunchArgument("nav_stuck_recovery_turn_duration_sec", default_value="1.0"),
            Node(
                package="vln_nav2_bridge",
                executable="vln_node_local",
                output="screen",
                parameters=[
                    {"use_sim_time": True},
                    {"image_topic": LaunchConfiguration("image_topic")},
                    {"compressed_image_topic": LaunchConfiguration("compressed_image_topic")},
                    {"odom_topic": LaunchConfiguration("odom_topic")},
                    {"require_fresh_image": LaunchConfiguration("require_fresh_image")},
                    {"nav_timeout_sec": LaunchConfiguration("nav_timeout_sec")},
                    {"nav_feedback_log_interval_sec": LaunchConfiguration("nav_feedback_log_interval_sec")},
                    {"inference_mode": LaunchConfiguration("inference_mode")},
                    {"allow_inference_fallback": LaunchConfiguration("allow_inference_fallback")},
                    {"force_cpu": LaunchConfiguration("force_cpu")},
                    {"gpu_device": LaunchConfiguration("gpu_device")},
                    {"model_startup_timeout_sec": LaunchConfiguration("model_startup_timeout_sec")},
                    {"inference_request_timeout_sec": LaunchConfiguration("inference_request_timeout_sec")},
                    {"model_python_executable": LaunchConfiguration("model_python_executable")},
                    {"live_image_snapshot_dir": LaunchConfiguration("live_image_snapshot_dir")},
                    {"visual_scan_enabled": LaunchConfiguration("visual_scan_enabled")},
                    {"visual_scan_steps": LaunchConfiguration("visual_scan_steps")},
                    {"visual_scan_step_rad": LaunchConfiguration("visual_scan_step_rad")},
                    {"visual_scan_settle_sec": LaunchConfiguration("visual_scan_settle_sec")},
                    {"visual_scan_min_confidence": LaunchConfiguration("visual_scan_min_confidence")},
                    {"visual_scan_spin_time_allowance_sec": LaunchConfiguration("visual_scan_spin_time_allowance_sec")},
                    {"visual_scan_spin_mode": LaunchConfiguration("visual_scan_spin_mode")},
                    {"visual_scan_angular_speed_rad_s": LaunchConfiguration("visual_scan_angular_speed_rad_s")},
                    {"cmd_vel_topic": LaunchConfiguration("cmd_vel_topic")},
                    {"semantic_exploration_enabled": LaunchConfiguration("semantic_exploration_enabled")},
                    {"clear_costmaps_before_nav": LaunchConfiguration("clear_costmaps_before_nav")},
                    {"nav_retry_on_stuck": LaunchConfiguration("nav_retry_on_stuck")},
                    {"nav_max_retries": LaunchConfiguration("nav_max_retries")},
                    {"nav_accept_distance_m": LaunchConfiguration("nav_accept_distance_m")},
                    {"nav_accept_distance_hold_sec": LaunchConfiguration("nav_accept_distance_hold_sec")},
                    {"nav_stuck_timeout_sec": LaunchConfiguration("nav_stuck_timeout_sec")},
                    {"nav_stuck_min_progress_m": LaunchConfiguration("nav_stuck_min_progress_m")},
                    {"nav_stuck_recovery_backup_speed_m_s": LaunchConfiguration("nav_stuck_recovery_backup_speed_m_s")},
                    {"nav_stuck_recovery_backup_duration_sec": LaunchConfiguration("nav_stuck_recovery_backup_duration_sec")},
                    {"nav_stuck_recovery_turn_speed_rad_s": LaunchConfiguration("nav_stuck_recovery_turn_speed_rad_s")},
                    {"nav_stuck_recovery_turn_duration_sec": LaunchConfiguration("nav_stuck_recovery_turn_duration_sec")},
                ],
            )
        ]
    )
